/**
 * Tailwind class-name helper — generated by `npx shadcn@latest init`.
 *
 * `cn(...inputs)` merges class lists deterministically and removes
 * conflicting Tailwind utilities (the last winner wins). Used by every
 * shadcn/ui primitive in src/components/ui to compose `className` props.
 *
 * Source-of-truth for the helper signature is the shadcn/ui CLI; do not
 * inline this elsewhere in the codebase — always import from '@/lib/utils'.
 */
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs));
}
