-- Migration 0003_users_is_minor.sql — Phase 1 Wave 6, Plan 12.
-- GDPR-02 minor-consent enforcement.
--
-- ─────────────────────────────────────────────────────────────────────────
-- DEVIATION (CR-01 fix, 2026-05-01): the original draft of this migration
-- attempted to add `users.is_minor` as a STORED generated column whose
-- expression referenced `CURRENT_DATE`. Postgres rejects that at apply time
-- with `ERROR: generation expression is not immutable` because
-- `CURRENT_DATE` is `STABLE`, not `IMMUTABLE`, and STORED generated columns
-- demand IMMUTABLE expressions. The whole minor-consent gate (Plan 12 /
-- `canActivate`) would have been broken at the schema layer.
--
-- Resolution: drop the generated-column approach and compute the minor
-- flag in application code. `src/server/auth/activate.ts` derives
-- `isMinor` from `users.date_of_birth` via the `isMinorAt(birthDate, now)`
-- helper in `src/lib/consent.ts` (UTC-anchored, deterministic across the
-- 16th-birthday day boundary). RLS / direct-Postgres consumers that need
-- the flag (none in Phase 1) can compute it inline as
-- `CURRENT_DATE - date_of_birth < INTERVAL '16 years'` in their own
-- SELECT predicate — that is allowed because predicates do not require
-- IMMUTABLE expressions.
--
-- This file therefore intentionally contains no DDL: it remains in the
-- migration sequence so `drizzle/meta/_journal.json` (idx 3) still points
-- at a valid file, but it makes no schema change. Subsequent migrations
-- (0004+) keep numbering consistent.
-- ─────────────────────────────────────────────────────────────────────────

-- No-op (see header rationale).
SELECT 1 WHERE FALSE;
